export enum ActionTypes {
  SET_MAIN_LIST = 'home/SET_MAIN_LIST',
  SET_FAVORITE_LIST = 'home/SET_FAVORITE_LIST',
  SET_FILTERS = 'home/SET_FILTERS',
  SET_LOADING = 'home/SET_LOADING',

  CHANGE_HISTORY = 'history/CHANGE_HISTORY',
  CHANGE_HISTORY_TYPE = 'history/CHANGE_HISTORY_TYPE',
}
